### ISSUE TITLE
Windows build documentation

### ISSUE THREAD

**Issue by adrianbroher** [freeorion/freeorion-sdk#10]
@geoffthemedio 

In #8 we tried to convince CMake to build the SDK with various generators and toolsets.  Could you please check if the configuration still works without those additional parameters (-T, -G) and we still get the desired SDK for the desired VisualStudio+toolset or if the `README.md` needs to be updated?

**Comment by geoffthemedio** [comment]
Ran in the 2010 command pompt. It defaulted to 2015 with no extra parameters beyond what's in the readme. Result built seemingly fine.

**Comment by adrianbroher** [comment]
Thanks for the feedback.

> Ran in the 2010 command pompt.

I checked if this is required.  Doesn't seem to be the case.  The build works as long as cmake is on the `PATH`.  So the documentation is up to date.

**Comment by geoffthemedio** [comment]
My point re: 2010 was that I generated the 2015 SDK within something other than the 2015 command prompt. My default cmd.exe shortcut goes to the 2010 version.
