### ISSUE TITLE
Mac OSX SDK: wrong library id names and paths in mach headers of shared libraries

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion-sdk#16]
Stumbled upon another issue with the shared libraries the cmake scripts produce. Noticed that in the `Ogg` and `Vorbis` binaries of the Ogg and Vorbis frameworks. The library paths as returned by the `otool` command are as follows:

```
user$ otool -L Ogg
Ogg:
    Ogg.framework/Versions/1.3.2/Ogg (compatibility version 0.8.2, current version 0.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

```
user$ otool -L Vorbis
Vorbis:
    Vorbis.framework/Versions/1.3.5/Vorbis (compatibility version 0.0.0, current version 0.0.0)
    Ogg.framework/Versions/1.3.2/Ogg (compatibility version 0.8.2, current version 0.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

When built and linked with the libraries containing these paths in their mach headers, the FO app immediately quits when launched, with the dynamic linker giving an error that it can't find the binary images.

What the paths (and id names) need to be is:

```
user$ otool -L Ogg
Ogg:
    @executable_path/../Frameworks/Ogg.framework/Versions/1.3.2/Ogg (compatibility version 0.8.2, current version 0.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

```
user$ otool -L Vorbis
Vorbis:
    @executable_path/../Frameworks/vorbis.framework/Versions/1.3.5/Vorbis (compatibility version 0.0.0, current version 0.0.0)
    @executable_path/../Frameworks/Ogg.framework/Versions/1.3.2/Ogg (compatibility version 0.8.2, current version 0.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

Of course that applies to all the dynamic libraries generated by the cmake scripts too (Python etc.).

**Comment by adrianbroher** [comment]
> What the paths (and id names) need to be is:

So… the rpath is wrong?  Are you sure?  I find it odd that the used library needs to know the location of the using executable.

**Comment by adrianbroher** [comment]
Probably relevant: http://www.dribin.org/dave/blog/archives/2009/11/15/rpath/

**Comment by Vezzra** [comment]
Yep, that worked. Setting the id names to `@rpath/<framework_name>.framework/Versions/<version>/<binary>` and adding `@loader_path/../Frameworks` to the "Runtime Search Paths" setting in the "Linking" section of the Xcode project build settings did the trick.

However, the id names still need to be adjusted - just `<framework_name>.framework/Versions/<version>/<binary>` is not sufficient. The `@rpath/` prefix is required.

**Comment by adrianbroher** [comment]
> Setting the id names to @rpath/<framework_name>.framework/Versions/<version>/<binary> and adding @loader_path/../Frameworks to the "Runtime Search Paths" setting in the "Linking" section of the Xcode project build settings did the trick.

We are talking about the build settings of freerion{,d,ca} here, right?

> However, the id names still need to be adjusted

I need to research how to set this in CMake.

**Comment by Vezzra** [comment]
> We are talking about the build settings of freerion{,d,ca} here, right?

Yes, however, I can (an do) specify these settings not on the level of the single build targets, but on the global project level, from where the build targets inherit them. I only ever specify build settings on the build target level if absolutely necessary (which means if other build targets would get messed up if passed the setting in question or something like that).

Makes maintaining easier, and avoids stupid errors if you miss to add/change/remove a setting everywhere it needs to apply.

**Comment by adrianbroher** [comment]
I have added a branch `fix-rpath-on-macosx`.   The single commit on that branch should fix the rpath for the `Ogg.framework`.  Can you check if the change works properly so I can apply it to all frameworks?

**Comment by Vezzra** [comment]
Yep, that works 👍

**Comment by adrianbroher** [comment]
Enabled RPATH for Vorbis, Ogg, Python and SDL framework with 4d9c44fd.

Closing, as this issue should be fixed in the latest master.

**Comment by Vezzra** [comment]
> Closing, as this issue should be fixed in the latest master.

Done: freeorion/freeorion@783f8dcae8c434709851cb40d0596f71bd4e3e61
