### ISSUE TITLE
[mac-support branch] libvorbis install fails

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion-sdk#2]
`cmake .`runs successfully, but the subsequent `cmake --build . --config RelWithDebInfo` fails with the following error message when trying to build target libvorbis:
```
Install the project...
-- Install configuration: "RelWithDebInfo"
CMake Error at cmake_install.cmake:31 (file):
  file INSTALL cannot find
  "/Users/user/SoftwareProjekte/FO/sdk/build/libvorbis-prefix/src/libvorbis/vorbis.pc".


make[3]: *** [install] Error 1
make[2]: *** [libvorbis-prefix/src/libvorbis-stamp/libvorbis-install] Error 2
make[1]: *** [CMakeFiles/libvorbis.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by Vezzra** [comment]
From what I've seen, it seems that the script is looking for `vorbis.pc` in the wrong subfolder. `build/libvorbis-prefix/src/libvorbis/` only contains the `*.in` files, the `*.pc` files are in `sdk/build/libvorbis-prefix/src/libvorbis-build/`. Don't know how to fix that though...

**Comment by adrianbroher** [comment]
Yeah, it's a minor bug in the libvorbis upstream CMake build.

The `patches` directory is full of things like that, where a condition is missing or, like here, a a wrong assumption of the current source directory is made.  Some time in the future I need to push those to upstreams.
