### ISSUE TITLE
compiling takes A LONG TIME

### ISSUE THREAD

**Issue by afwbkbc** [freeorion/freeorion-sdk#24]
Takes about 5 minutes to build freeorion on liquid-cooled AMD FX-9590 8 x 5.2GHz, with every core is loaded 100%. This seems to be too long for such a small game (even boost is built much faster, while libpng is built in 2 seconds). Not sure if problem of MSVS itself, but mingw builds are typically much faster (maybe 10 times faster) without any drawbacks, so maybe you could consider replacing MSVC for mingw on windows. With such frequent updates compilation is painful.

**Comment by adrianbroher** [comment]
This issue has no relation to the freeorion-sdk.

> With such frequent updates compilation is painful.

Use the weekly builds if you want to track most recent development.

**Comment by Vezzra** [comment]
@afwbkbc, AFAIK most if not all of the FO devs don't have a machine that comes even close to your specs. A full rebuild takes maybe 15 min on my Mac, and over half an hour on my Windows machine. A five min build time would be *heaven* for me.

You seem to have very different expectations than we when it comes to how fast certain things should/need to be.

I'm telling you this so you maybe can better understand why your recent requests are unreasonable in our eyes (and why they have been closed). The things you brought up are no issue at all in our eyes, and, as @adrianbroher mentioned elsewhere, we have far more pressing issues to deal with.

This is an open source project carried only by the efforts of volunteers who do all this in their free time. We just don't have the resources at our disposal as a big commercial title. Please keep that in mind.
