### ISSUE TITLE
Symbol visibility for Boost libraries

### ISSUE THREAD

**Issue by memem359** [freeorion/freeorion-sdk#27]
Since the FreeOrion code is being compiled with -fvisibility=hidden for Clang:
https://github.com/freeorion/freeorion/commit/d77858f3cf7208fc1b606f559b72b55fc6d35776

... shouldn't that also be done for the SDK?
I did a search through the CMakeLists.txt file, and didn't get a hit.
Travis builds are getting a lot of warning messages (for the regular FO build) due to the current Boost libraries and the visibility setting mismatch.

**Comment by Vezzra** [comment]
> Travis builds are getting a lot of warning messages due to the current Boost libraries and the visibility setting mismatch.

Hm, if I understand the `-fvisibility=hidden` feature correctly, this is about reducing the amount of exported symbols of the unit being compiled. So I wonder why a "visibility mismatch" would cause compiler warnings, but I'm not really very knowledgeable about this.

@adrianbroher?

**Comment by memem359** [comment]
I don't pretend to have more than surface knowledge about how the linker handles visibility.

But from doing web searches, it seems universal that (1) these type of boost compiler warnings are due to the Boost libraries being built with the default setting and someone compiling the rest of their code with the hidden setting, and (2) "in for a penny, in for a pound" - better to choose a setting, but apply it everywhere.

@Vezzra 
Did you make the Mac SDK using CMake, or by other means?
I almost have it working with CMake, but there are some peculiar problems which I think are specific to my Mac setup. I might have a git commit & PR ready in a week or two. (Need to learn more CMake!) I'll start up a forum topic when I'm almost ready.

**Comment by Vezzra** [comment]
> Did you make the Mac SDK using CMake, or by other means?

If you're referring to the current version of the SDK, then yes, in the sense that I use the SDK built by the FO SDK cmake scripts. However, I didn't author those scripts, that has been @adrianbroher. My own cmake skills are rudimentary at best.

I *did* maintain the FO SDK for OSX before @adrianbroher made those cmake scripts. Back then the SDK was made by manually building all the dependencies and putting together the SDK package. Which was a pain, especially when switching to a new boost version became necessary.

The SDK cmake scripts made things a *lot* easier.

> I almost have it working with CMake

You mean, you can't build the SDK with the cmake scripts as they are provided ("out-of-the-box")? That shouldn't be the case... what are the issues you ran into? Have you tried using the prebuilt SDK package?

**Comment by memem359** [comment]
From the base version, my problem is trivial but still annoys me.
During the pre-pack (almost last step), it generates an error when deleting the "dep" directory. I still have a usable dep.tar.bz2 and bootstrap in my INSTALL directory, but it would be nice if the entire sequence from start-to-DMG was working. I just need to figure out why my particular system is having problems with such a simple action.

I was also experimenting with some changes which would be nice to have working.
- I've already made some comments about PR #21 . We can use i386 OR x86_64, but it would be more convenient to have both in universal libraries to make any transitions easier. I've found the problem in libpng, but it requires modifying some cmake generating functions. (Figuring out how to fix the cmake output of a generated script is making my head spin.) Still need to figure out which script is making the (bad) pyconfig.h
- The other issue was turning on the -fvisibility=hidden compiler flags, but I think I have that figured out. (Had to learn about cmake, setting variables, and `force`.)

**Comment by memem359** [comment]
A couple of notes about this issue.

We will have to switch from static to shared libraries.
http://boost-log.sourceforge.net/libs/log/doc/html/log/installation/config.html
Boost Log library must be built as a shared object.

More importantly, there is a problem with having visibility=hidden for the iostreams library.
In the file iostreams/filter/zlib.hpp, there are options for Windows linking, but there are no options for visibility=hidden for other platforms.

**Comment by agrrr3** [comment]
Boost log sais "if your application consists of more than one module (e.g. an exe and one or several dll's) that use Boost.Log, the library must be built as a shared object"
In my understanding its not the case at the moment. We only have the gigi dlls and if i grepped correctly we dont use boost logging there.

**Comment by memem359** [comment]
@agrrr3 We do have more than one module (3 different clients, Common shlib, Parse shlib).

Currently the Mac build is having troubles with Logger, which is being compiled in the Common library. Only log messages coming inside that library are working. Any log messages coming from code compiled outside Common are being sent to stdout.

It is also the case that to get the Boost visibility settings to work (for the other libraries) requires using the DYN_LINK macros, which again means needing shared libraries for the Mac build.

**Comment by memem359** [comment]
Closing this issue. (This should be resolved when the Boost libraries are switched from static to shared, which will make the Logger work.)
