### ISSUE TITLE
v7 but label=6 in docker file

### ISSUE THREAD

**Issue by agrrr3** [freeorion/freeorion-sdk#28]
The master-branch and v7-tag both have label=6 in the docker file. Should that not have been bumped up and deployed? (I guess to 7 for v7 ??). 

"History":
label version="6" for  https://github.com/freeorion/freeorion-sdk/blob/v7/Dockerfile
label version="6" for  https://github.com/freeorion/freeorion-sdk/blob/v6/Dockerfile
label version="6" for  https://github.com/freeorion/freeorion-sdk/blob/v5/Dockerfile
label version="5" for  https://github.com/freeorion/freeorion-sdk/blob/v4/Dockerfile

**Comment by adrianbroher** [comment]
> Should that not have been bumped up and deployed?

No, why should it?
