### ISSUE TITLE
[mac-support branch] patch step for target python-cmake fails

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion-sdk#3]
Application of the patch fails with the following error message:
```
[ 56%] Performing patch step for 'python-cmake'
patching file cmake/libpython/CMakeLists.txt
Hunk #1 FAILED at 311.
1 out of 1 hunk FAILED -- saving rejects to file cmake/libpython/CMakeLists.txt.rej
make[2]: *** [python-cmake-prefix/src/python-cmake-stamp/python-cmake-patch] Error 1
make[1]: *** [CMakeFiles/python-cmake.dir/all] Error 2
make: *** [all] Error 2
```
Attached the CMakeLists.txt.rej the error message refers to:
[CMakeLists.txt.rej.zip](https://github.com/freeorion/freeorion-sdk/files/193240/CMakeLists.txt.rej.zip)

**Comment by adrianbroher** [comment]
The python cmake build system is an external project, that allows python to be built with cmake.  They added python3 support and now some patches don't apply anymore poperly.  It is a bad idea anyway to point just to their master.  I'm pinning this for now to a specific, working commit.

**Comment by adrianbroher** [comment]
If it doesn't work right out of the box try deleting `python-cmake-prefix` folder and build again.
