### ISSUE TITLE
Max OSX - Boost fails to find SDKs

### ISSUE THREAD

**Issue by dbenage-cx** [freeorion/freeorion-sdk#30]
OSX: 10.12.5  XCode: 8
Build fails during boost build:
```
/opt/projects/freeorion-sdk/build-cm/boost-prefix/src/boost/tools/build/src/build/feature.jam:494: in validate-value-string from module feature
error: "10.9" is not a known value of feature <macosx-version-min>
error: legal values:
/opt/projects/freeorion-sdk/build-cm/boost-prefix/src/boost/tools/build/src/build/feature.jam:364: in expand-subfeatures-aux from module feature
/opt/projects/freeorion-sdk/build-cm/boost-prefix/src/boost/tools/build/src/build/feature.jam:425: in feature.expand-subfeatures from module feature
/opt/projects/freeorion-sdk/build-cm/boost-prefix/src/boost/tools/build/src/build/build-request.jam:20: in apply-to-property-set from module build-request
(builtin):-1: in sequence.transform from module sequence
/opt/projects/freeorion-sdk/build-cm/boost-prefix/src/boost/tools/build/src/build/build-request.jam:32: in build-request.expand-no-defaults from module build-request
/opt/projects/freeorion-sdk/build-cm/boost-prefix/src/boost/tools/build/src/build-system.jam:594: in load from module build-system
/opt/projects/freeorion-sdk/build-cm/boost-prefix/src/boost/tools/build/src/kernel/modules.jam:295: in import from module modules
/opt/projects/freeorion-sdk/build-cm/boost-prefix/src/boost/tools/build/src/kernel/bootstrap.jam:139: in boost-build from module
/opt/projects/freeorion-sdk/build-cm/boost-prefix/src/boost/boost-build.jam:17: in module scope from module
```
[build_log.txt](https://github.com/freeorion/freeorion-sdk/files/1048347/build_log.txt)

Resolved by adding symlink, as noted in workaround for https://svn.boost.org/trac/boost/ticket/10275.

**Comment by memem359** [comment]
We had a discussion around the same time about how cmake was invoked.
Do you still see this problem, or is it fixed now?

> The README has cmake .. to get everything set up before the build.
I added a comment to the README to use instead
cmake -G Xcode -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk ..
(or whatever path is appropriate) for a Mac system, since that is the command that the Travis check uses.

**Comment by dbenage-cx** [comment]
@memem359 Appears to work, but the resulting freeorion build was only briefly tested.
[gen_build_log.txt](https://github.com/freeorion/freeorion-sdk/files/1048358/gen_build_log.txt)

Since the path is especially long, surely there is another method to determine this directory?

**Comment by memem359** [comment]
I'm still learning CMake by trial-and-error, modifying the existing script.

I'll see about making that SYSROOT path as a default argument, making sure it can be overwritten if necessary.

**Comment by dbenage-cx** [comment]
From what I have read, `CMAKE_OSX_SYSROOT` is defined by CMake if not specified.
Did not check if that is a change since 3.5.x (which was used above), or was resolved in later version.
Upgrading to 3.8.2 (via homebrew) allows the simpler form:
```
cmake -G Xcode ..
cmake --build . --config RelWithDebInfo
```
But still fails for `cmake ..` as per the original log excerpt.

**Comment by memem359** [comment]
If for some reason having a default value in the file is worthwhile, it is only a 2 line edit.
As you say, the important thing is to have "Xcode" as the generator for that initial step.

**Comment by adrianbroher** [comment]
Boost b2 searches in the wrong place for the compiler and assumes it's an old Xcode installation, hence looking up `/Developer`.

Compare:

Travis:
```
notice: [darwin]  compiler command: /Applications/Xcode.app/Contents/Developer/usr/bin
notice: [darwin]  install root: /Applications/Xcode.app/Contents/Developer
```

Yours:
```
notice: [darwin]  compiler command: /usr/bin
notice: [darwin]  install root: /Developer
```

What is the output of `xcode-select --print-path`?

**Comment by dbenage-cx** [comment]
> What is the output of xcode-select --print-path?

`/Applications/Xcode.app/Contents/Developer`

**Comment by memem359** [comment]
@dbenage-cx  To go back to your message from yesterday, it sounded like it works when you used the Xcode generator option `-G Xcode`. Is that correct? If so, then modifying the README to mention that should be enough to close this issue. (I should probably separate that commit/PR from the other work on the Mac SDK.)

**Comment by dbenage-cx** [comment]
Apparently I was on your PR branch when building freeorion, it builds but freeorion fails unless both are switched to x86_64.
There are also cmake changes as recent as 3.8.0 wrt xcode 8.0 and `CMAKE_OSX_SYSROOT` (avoiding back-linking, see history of https://github.com/Kitware/CMake/commits/master/Modules/Platform/Darwin-Initialize.cmake).  To note any differences I've built with both versions.

Given cloned repos in freeorion-sdk and freeorion:
```
freeorion-sdk $mkdir build-id && cd build-id
freeorion-sdk/build-id $cmake -G Xcode .. 2>&1 | tee cmake_gen.log
freeorion-sdk/build-id $cmake --build . 2>&1 | tee cmake_build.log
(mount resulting .dmg, copy dep.tar.bz2 to freeorion directory)

freeorion $tar -xjf dep.tar.bz2 -C Xcode
(open XCode: build clean, build)
```

Freeorion fails building during client link when using freeorion-sdk/master and freeorion/master.

CMake 3.5.1: [i386.tar.gz](https://github.com/freeorion/freeorion-sdk/files/1050168/i386.tar.gz)

CMake 3.8.2: [i386-cmake_3_8_2.zip](https://github.com/freeorion/freeorion-sdk/files/1050183/i386-cmake_3_8_2.zip)


Diffs switching freeorion and freeorion-sdk to x86_64/Native Arch: https://gist.github.com/dbenage-cx/f5984a6cfd5b32416b9980088ea0fff1

CMake 3.5.1 + diffs: [x86_64.tar.gz](https://github.com/freeorion/freeorion-sdk/files/1050169/x86_64.tar.gz)

CMake 3.8.2 + diffs: [x86_64-cmake_3_8_2.tar.gz](https://github.com/freeorion/freeorion-sdk/files/1050170/x86_64-cmake_3_8_1.tar.gz)

**Comment by adrianbroher** [comment]
So there is no issue after all?

> your PR branch.
> Freeorion fails building during client link when using freeorion-sdk/master and freeorion/master.

Please clarify.

**Comment by dbenage-cx** [comment]
Changing readme to `cmake -G Xcode ..` for OSX would resolve issue, but creates a new one wrt linking freeorion.
Additionally, it may result in other issues on cmake < 3.8.0 without `-DCMAKE_OSX_SYSROOT=...`

Excerpt from freeorion client target log (i386, added line breaks for first line):
```
ld: warning:
ld: warning: ignoring file /opt/projects/FreeOrion/Xcode/dep/lib/libpng.a,
 file was built for archive which is not the architecture being linked (i386): /opt/projects/FreeOrion/Xcode/dep/lib/libpng.a
ignoring file /opt/projects/FreeOrion/Xcode/dep/lib/libGLEW.a,
 file was built for archive which is not the architecture being linked (i386): /opt/projects/FreeOrion/Xcode/dep/lib/libGLEW.a

Undefined symbols for architecture i386:\
  "___GLEW_EXT_framebuffer_object", referenced from:\
      GG::SDLGUI::SetVideoMode(GG::X, GG::Y, bool, bool) in libGG.a(SDLGUI.o)\
      GG::SDLGUI::FramebuffersAvailable() const in libGG.a(SDLGUI.o)\

...<snip>...

ld: symbol(s) not found for architecture i386\
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by dbenage-cx** [comment]
Apparently, libpng16.a and libGLEW.a were changed to libpng16d.a and libGLEWd.a (within dep.tar.bz2).
Manually renaming those results in successful freeorion build.

**Comment by adrianbroher** [comment]
Well, given there was no response I assume this issue is related to some unspecified PR and not a problem with the actual SDK.  Closing this.

**Comment by memem359** [comment]
@dbenage-cx 
> Apparently I was on your PR branch when building freeorion, it builds but freeorion fails unless both are switched to x86_64.

That's why I made a bunch of cross-references for those 2 PRs and mentioned it in the notes.

> There are also cmake changes as recent as 3.8.0 wrt xcode 8.0 and CMAKE_OSX_SYSROOT (avoiding back-linking...

Yeah, I'm using 3.8.1, so I didn't think about what would happen with older versions.
If `CMAKE_OSX_SYSROOT` is set after the CMakeLists.txt call `project(FreeOrionSDK)`, then I can add a default value if SYSROOT is not set by that point. It wouldn't affect 3.8.1, but it might help your situation with earlier CMake versions?

**Comment by dbenage-cx** [comment]
@memem359 If it is acceptable to maintainer, may be cleaner to change required CMake version to 3.8.0
