### ISSUE TITLE
Switch Boost library version?

### ISSUE THREAD

**Issue by memem359** [freeorion/freeorion-sdk#35]
The FO-SDK currently uses Boost v1.59.

I noticed a recent FO PR https://github.com/freeorion/freeorion/pull/1775
... where it sounds like Fedora users might want Boost v1.63 or higher to resolve certain ptr problems.

Question: Would it be beneficial to switch Boost versions (1.59 to 1.63) for everyone?
I don't know what safeguards are in place.
Or maybe this kind of action is strictly forbidden (except to select experts).

I might be interested in this switch for the Mac. There is a request (in PR #29) to have B2 handle renaming shared library path names. This was broken for 1.59, but I found a discussion thread where someone claimed it was fixed by 1.63. I'd be willing to check this, but I want to know before putting in the work if this is a viable solution or not.

(Also, I don't have a Windows system, so someone else would have to test for side effects. I wouldn't want to make life difficult for the Windows users, if switching Boost versions would cause a headache.)

**Comment by Vezzra** [comment]
If it helps solving the issues on Mac and makes switching to 64 bit possible, sure, why not. Can't tell however which issues that might cause on the other platforms.

**Comment by adrianbroher** [comment]
Implemented with 56279405cf1b51fdb73be0c8fc22f579d9f53f7d, boost 1.66 will be available with the next release of the SDK.
