### ISSUE TITLE
Upgrade docker image to ubuntu:18.04

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion-sdk#37]
Is there plan to update test docker image to ubuntu:18.04? It have newer 1.65 boost version which allows boost to catch system errors without false positives for https://github.com/freeorion/freeorion/pull/2050

**Comment by o01eg** [comment]
@agrrr3 It's placed in this repository.

**Comment by Vezzra** [comment]
> Is there plan to update test docker image to ubuntu:18.04?

Eventually, I guess. But 18.04 is brand new, I'd at least wait for the first maintenance/bugfix release before upgrading the docker image.

@adrianbroher?

**Comment by adrianbroher** [comment]
Eh, I don't know.  While I understand where the request comes from I consider the CI as a check against some of the minimum dependencies required.  Bumping those makes the current image less useful.

I think boost 1.65 is way to recent  for a minimum requirement.

Feel free to discuss what we should hold as minimum requirements for freeorion in general and I will change the build accordingly.

**Comment by Vezzra** [comment]
> I think boost 1.65 is way to recent for a minimum requirement.

Excellent point.

**Comment by o01eg** [comment]
Actually any plans of migration to python3 require to upgrade base docker image: https://freeorion.org/forum/viewtopic.php?f=9&t=11181
