### ISSUE TITLE
MSVC2017 - Building boost fails

### ISSUE THREAD

**Issue by Morlic-fo** [freeorion/freeorion-sdk#52]
## Environment
OS: Win10
Compiler: MSVC2017

## Problem description:
When building the SDK as per instructions, the boost project will fail to build with MSVC2017 because it looks for clang (and fails to find which is expected). The same problem has previously been reported in [the forum](https://www.freeorion.org/forum/viewtopic.php?f=24&t=11375).

Relevant log:
```
CUSTOMBUILD : warning : toolset clang-linux initialization: can not find tool clang++ [D:\FOTestBuild\freeorion-sdk\build\boost.vcxproj]
CUSTOMBUILD : warning : initialized from D:\FOTestBuild\freeorion-sdk\build\boost-config.jam:20 [D:\FOTestBuild\freeorion-sdk\build\boost.vcxproj]
  '"clang++"' is not recognized as an internal or external command,
  operable program or batch file.
  notice: will use 'clang++' for clang-linux, condition <toolset>clang-linux
```

As a workaround, I deleted the following lines
https://github.com/freeorion/freeorion-sdk/blob/master/boost-config.jam.in#L15-L20
which allowed me to build the SDK just fine.

## Steps to reproduce:
```
git clone https://github.com/freeorion/freeorion-sdk
cd freeorion-sdk
mkdir build && cd build
cmake ..
cmake --build . --config RelWithDebInfo
```

## Expected result:
Do not try to use clang under windows

**Comment by o01eg** [comment]
Looks strange as AppVeyor builds it correctly. Could you try to declare toolset and generator?

**Comment by Morlic-fo** [comment]
Maybe AppVeyor actually does find clang?
https://ci.appveyor.com/project/freeorion/freeorion-sdk/builds/27857341/job/vj6tn130cv3fncld#L2459

```notice: will use 'clang++' for clang-linux, condition <toolset>clang-linux-8.0.0```

**Comment by o01eg** [comment]
Looks like so, because this part was introduced in https://github.com/freeorion/freeorion-sdk/commit/bdbb4f9252c786084c63d48a3458b7d8f0149306#diff-f899476ad7c0e718fe46010615606559

**Comment by o01eg** [comment]
Maybe user-config.jam should include clang only for MacOS.

**Comment by o01eg** [comment]
@Morlic-fo Could you try this PR? #53
