### ISSUE TITLE
Building SDK with MSVC 2019

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion-sdk#59]
I installed MSVC 2019 and tried to build the SDK. I ran into issues:

1) GLEW 2.1.0 fails to link, as discussed here https://github.com/nigels-com/glew/issues/238#issuecomment-543442437 and possibly fixed by this: https://github.com/nigels-com/glew/commit/4bbe8aa2ab70a6eb847ee5751735422d0ba623cd but I don't know how to apply that when building the SDK. Editing the GLEW CMakeLists.txt after the build failed once and re-starting it doesn't restart the build.

2) I had to modify the build command slightly to specify the Win32 target: `C:\Users\Geoff\Desktop\freeorion-sdk\build>cmake .. -G "Visual Studio 16 2019" -A Win32`

**Comment by geoffthemedio** [comment]
Trying with setting the newest snapshot URL in Source.cmake:
````
set(GLEW_URL https://sourceforge.net/projects/glew/files/glew/snapshots/glew-20200115.tgz)
set(GLEW_MD5 ffaca6d1536a9eb36b9c00f29c11065a)
````

**Comment by o01eg** [comment]
@geoffthemedio I've opened PR to solve issue with glew.

**Comment by geoffthemedio** [comment]
The SDK built OK with MSVC2019 using the hard-coded source snapshot URL as above.
