### ISSUE TITLE
Windows - CMake output has -prefex on dir names

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion-sdk#7]
As in the attached, the output of the generate step with the CMake GUI has -prefix on the dependency directory names.

The SDK build in MSVC 2015 from the solution still starts up and finishes at least a few projects, so it might not be an practical problem.

![sdk_configure_output-prefix](https://cloud.githubusercontent.com/assets/11386908/15705178/630a8eba-27ee-11e6-878c-a016cef2e583.png)

**Comment by adrianbroher** [comment]
> The SDK build in MSVC 2015 from the solution still starts up and finishes at least a few projects, so it might not be an practical problem.

It isn't a problem at all.  The SDK is composed into the INSTALL directory and packaged to from the content of that directory (given the whole build was successful).

**Comment by geoffthemedio** [comment]
Still looks weird, but OK.

**Comment by adrianbroher** [comment]
Every dependency has it's own prefix directory, where it downloads, unpacks, configures and builds the dependency in question to avoid conflicts.  Only the installation step installs the dependencies into the INSTALL directory with the SDK file layout you would expect. An additional target packs the contents of the INSTALL directory into a zip file.

**Comment by geoffthemedio** [comment]
Maybe your use of "prefix" doesn't mean what I'd expect...
