### ISSUE TITLE
CI broken for pull requests

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion-sdk#89]
Somehow other then Github Actions CI checks not works with recent PRs.

**Comment by Vezzra** [comment]
Unfortunately I can't offer much assistance. I've never dealt with all the CI and Github Actions stuff.

Can anyone offer any help with this...?

**Comment by geoffthemedio** [comment]
Is Travis CI needed anymore for the SDK?

**Comment by o01eg** [comment]
I think yes because Github Actions doesn't produce correct SDK for MacOS while Travis CI does.

**Comment by o01eg** [comment]
Alternatively maybe it possible to return back to manual release.

**Comment by geoffthemedio** [comment]
Apparently my personal Travis CI account was allotted all the free minutes, which the FreeOrion organization account can't use? Can we run the SDK build via my account somehow? Perhaps I need to clone the SDK repository? Can we then get that file into the FreeOrion account SDK releases list?

**Comment by o01eg** [comment]
I think it possible. You just need to push v13 tag to your own fork of freeorion-sdk and change tokens as current one is expired.

**Comment by geoffthemedio** [comment]
> change tokens

how / where do I do that?

**Comment by o01eg** [comment]
Not sure. Personal token should be encrypted for Travis CI as it published in repo compared to Github Actions where secret environment set in settings of repo.

**Comment by geoffthemedio** [comment]
There are several overly complicated lists of instructions for how to do TravisCI related stuff in various places. Best I can tell, I need some command line thing that works in bash to use their API to get an encrypted token I could put into travis.yml, so I don't know if or how I can get the appropriate token to enable me to run TravisCI builds.

**Comment by o01eg** [comment]
I've tried to generate SDK in `o01eg/freeorion-sdk` and got fail with MacOS https://app.travis-ci.com/github/o01eg/freeorion-sdk/jobs/572450153

**Comment by o01eg** [comment]
Windows still works https://github.com/o01eg/freeorion-sdk/releases

**Comment by geoffthemedio** [comment]
> I also sent Travis CI support a (repeated) question about how to use the credits on my account for FreeOrion builds. Hopefully this time they'll address that issue.

Apparently "The credits allocated to [a] user account cannot be used to trigger builds on [an] organizational account."

**Comment by o01eg** [comment]
Even Android release works.

**Comment by geoffthemedio** [comment]
For OSX, it seems that homebrew.bintray.com is offline due to an expired certificate. I can't access it via web browser, and the build log says:
````
==> Downloading https://homebrew.bintray.com/bottles/gpatch-2.7.6.high_sierra.bottle.tar.gz
curl: (22) The requested URL returned error: 502 Bad Gateway
Error: Failed to download resource "gpatch"
Download failed: https://homebrew.bintray.com/bottles/gpatch-2.7.6.high_sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://ftp.gnu.org/gnu/patch/patch-2.7.6.tar.xz
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html
````

**Comment by o01eg** [comment]
I suppose it about that error: https://github.com/Homebrew/discussions/discussions/1248

**Comment by o01eg** [comment]
It possible we need to remove `HOMEBREW_NO_AUTO_UPDATE=1` to update homebrew but we disabled it because update was broken.

**Comment by o01eg** [comment]
> Apparently "The credits allocated to [a] user account cannot be used to trigger builds on [an] organizational account."

What if login via org account as ask as it? Someone still need to login into it to get token anyway.

**Comment by o01eg** [comment]
Looks like it works https://github.com/o01eg/freeorion-sdk/releases/tag/v13

**Comment by Vezzra** [comment]
According to the instructions @adrianbroher gave me for making a new SDK release, pushing the release tag should trigger the build of the SDK. Here are the instructions as he sent them to me back when he cmakified the SDK builds (translated into English):

> 1) Update DIST_VERSION in CMakeList.txt
> 2) Create new entry in ChangeLog.md with version number and date
> 3) Create annotated git tag with message "Release <X> of the FreeOrionSDK"
> 4) Wait until TracisCI and AppVeyor have completed the build - the CI will create a release draft and send a notification by email once the builds have completed
> 5) Verify that the tag is correct and all build artefacts have been attached correctly
> 6) Copy the entry in the changelog into the description (of the release draft)
> 7) Publish the release

However, if that does not work anymore because of the changes with TravisCI and our problem, that all the free minutes are now bound to @geoffthemedio's account, we obviously need some workaround (or a completely new solution).

@geoffthemedio forking the SDK repo to his personal account and following the above steps up until 5), and then proceed with the rest manually (create a new release in the SDK repo in the organizational account, copy the build artifacts over, edit the description accordingly and publish the release) should work IMO.

If that really works, this is probably the best workflow for now I guess (until we can fix the process)...

However, I don't know how to fix that token stuff...

**Comment by geoffthemedio** [comment]
An alternative is probably to pick a plan for the freeorion org TravisCI account. Probably that would work temporarily as a trial account, and then probably they'd allocate some more open-source minutes upon request. I'm reluctant to do this as it requires providing credit card info, though.

But regardless, I seemingly don't have any way to encrypt a token without a linux command line.

**Comment by Vezzra** [comment]
@geoffthemedio, that does not sound much less complicated than doing the final steps of releasing the SDK manually, as outlined above. So not really worth using the option where you have to provide cradit card info...

**Comment by o01eg** [comment]
Could be closed with move to Github Actions CI
